# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Keylogger_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiKeylogger(object):
    def setup(self, Keylogger):
        Keylogger.setObjectName("Keylogger")
        Keylogger.resize(163, 190)
        Keylogger.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        Keylogger.setWindowTitle("Keylogger")
        self.StartButton = QtWidgets.QPushButton(Keylogger)
        self.StartButton.setGeometry(QtCore.QRect(10, 10, 141, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartButton.sizePolicy().hasHeightForWidth())
        self.StartButton.setSizePolicy(sizePolicy)
        self.StartButton.setObjectName("StartButton")
        self.SetButton = QtWidgets.QPushButton(Keylogger)
        self.SetButton.setGeometry(QtCore.QRect(10, 60, 141, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetButton.sizePolicy().hasHeightForWidth())
        self.SetButton.setSizePolicy(sizePolicy)
        self.SetButton.setObjectName("SetButton")
        self.EndKeyOutput = QtWidgets.QLineEdit(Keylogger)
        self.EndKeyOutput.setGeometry(QtCore.QRect(10, 140, 141, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndKeyOutput.sizePolicy().hasHeightForWidth())
        self.EndKeyOutput.setSizePolicy(sizePolicy)
        self.EndKeyOutput.setReadOnly(True)
        self.EndKeyOutput.setObjectName("EndKeyOutput")
        self.label = QtWidgets.QLabel(Keylogger)
        self.label.setGeometry(QtCore.QRect(10, 120, 47, 14))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")

        self.RetranslateUi(Keylogger)
        QtCore.QMetaObject.connectSlotsByName(Keylogger)

    def RetranslateUi(self, Keylogger):
        _translate = QtCore.QCoreApplication.translate
        self.StartButton.setText(_translate("Keylogger", "Start"))
        self.SetButton.setText(_translate("Keylogger", "Set end-key"))
        self.label.setText(_translate("Keylogger", "End-key:"))
